[package]
name = "activitypub"
version = "0.1.0"
edition = "2021"

[dependencies]
activitystreams = "0.7.0-alpha.24"
axum = "0.6.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2.4.0"
